//AUTOGENERATED FILE FROM png2asset
// Conversion args: /obj_calculator.png -spr8x8 -o /ch1_obj_calc.c

#ifndef METASPRITE_ch1_obj_calc_H
#define METASPRITE_ch1_obj_calc_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ch1_obj_calc_TILE_ORIGIN 0
#define ch1_obj_calc_TILE_W 8
#define ch1_obj_calc_TILE_H 8
#define ch1_obj_calc_WIDTH 16
#define ch1_obj_calc_HEIGHT 16
#define ch1_obj_calc_TILE_COUNT 4
#define ch1_obj_calc_PALETTE_COUNT 1
#define ch1_obj_calc_COLORS_PER_PALETTE 4
#define ch1_obj_calc_TOTAL_COLORS 4
#define ch1_obj_calc_PIVOT_X 8
#define ch1_obj_calc_PIVOT_Y 8
#define ch1_obj_calc_PIVOT_W 16
#define ch1_obj_calc_PIVOT_H 16
extern const metasprite_t* const ch1_obj_calc_metasprites[1];

BANKREF_EXTERN(ch1_obj_calc)

extern const palette_color_t ch1_obj_calc_palettes[4];
extern const uint8_t ch1_obj_calc_tiles[64];

#endif
