//AUTOGENERATED FILE FROM png2asset
// Conversion args: /obj_ball.png -b 255 -o /ch1_obj_ball.c

#ifndef METASPRITE_ch1_obj_ball_H
#define METASPRITE_ch1_obj_ball_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ch1_obj_ball_TILE_ORIGIN 0
#define ch1_obj_ball_TILE_W 8
#define ch1_obj_ball_TILE_H 16
#define ch1_obj_ball_WIDTH 16
#define ch1_obj_ball_HEIGHT 16
#define ch1_obj_ball_TILE_COUNT 4
#define ch1_obj_ball_PALETTE_COUNT 1
#define ch1_obj_ball_COLORS_PER_PALETTE 4
#define ch1_obj_ball_TOTAL_COLORS 4
#define ch1_obj_ball_PIVOT_X 8
#define ch1_obj_ball_PIVOT_Y 8
#define ch1_obj_ball_PIVOT_W 16
#define ch1_obj_ball_PIVOT_H 16
extern const metasprite_t* const ch1_obj_ball_metasprites[1];

BANKREF_EXTERN(ch1_obj_ball)

extern const palette_color_t ch1_obj_ball_palettes[4];
extern const uint8_t ch1_obj_ball_tiles[64];

#endif
