//AUTOGENERATED FILE FROM png2asset
// Conversion args: /baby_sitting.png -spr8x8 -o /ch1_baby_sitting.c

#ifndef METASPRITE_ch1_baby_sitting_H
#define METASPRITE_ch1_baby_sitting_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ch1_baby_sitting_TILE_ORIGIN 0
#define ch1_baby_sitting_TILE_W 8
#define ch1_baby_sitting_TILE_H 8
#define ch1_baby_sitting_WIDTH 32
#define ch1_baby_sitting_HEIGHT 40
#define ch1_baby_sitting_TILE_COUNT 12
#define ch1_baby_sitting_PALETTE_COUNT 3
#define ch1_baby_sitting_COLORS_PER_PALETTE 4
#define ch1_baby_sitting_TOTAL_COLORS 12
#define ch1_baby_sitting_PIVOT_X 16
#define ch1_baby_sitting_PIVOT_Y 20
#define ch1_baby_sitting_PIVOT_W 32
#define ch1_baby_sitting_PIVOT_H 40
extern const metasprite_t* const ch1_baby_sitting_metasprites[1];

BANKREF_EXTERN(ch1_baby_sitting)

extern const palette_color_t ch1_baby_sitting_palettes[12];
extern const uint8_t ch1_baby_sitting_tiles[192];

#endif
