//AUTOGENERATED FILE FROM png2asset
// Conversion args: /obj_book.png -b 255 -o /ch1_obj_book.c

#ifndef METASPRITE_ch1_obj_book_H
#define METASPRITE_ch1_obj_book_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ch1_obj_book_TILE_ORIGIN 0
#define ch1_obj_book_TILE_W 8
#define ch1_obj_book_TILE_H 16
#define ch1_obj_book_WIDTH 16
#define ch1_obj_book_HEIGHT 16
#define ch1_obj_book_TILE_COUNT 4
#define ch1_obj_book_PALETTE_COUNT 1
#define ch1_obj_book_COLORS_PER_PALETTE 4
#define ch1_obj_book_TOTAL_COLORS 4
#define ch1_obj_book_PIVOT_X 8
#define ch1_obj_book_PIVOT_Y 8
#define ch1_obj_book_PIVOT_W 16
#define ch1_obj_book_PIVOT_H 16
extern const metasprite_t* const ch1_obj_book_metasprites[1];

BANKREF_EXTERN(ch1_obj_book)

extern const palette_color_t ch1_obj_book_palettes[4];
extern const uint8_t ch1_obj_book_tiles[64];

#endif
