//AUTOGENERATED FILE FROM png2asset
// Conversion args: /ch2_textbook.png -sw 8 -sh 8 -spr8x8 -o /ch2_textbook.c

#ifndef METASPRITE_ch2_textbook_H
#define METASPRITE_ch2_textbook_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ch2_textbook_TILE_ORIGIN 0
#define ch2_textbook_TILE_W 8
#define ch2_textbook_TILE_H 8
#define ch2_textbook_WIDTH 8
#define ch2_textbook_HEIGHT 8
#define ch2_textbook_TILE_COUNT 1
#define ch2_textbook_PALETTE_COUNT 1
#define ch2_textbook_COLORS_PER_PALETTE 4
#define ch2_textbook_TOTAL_COLORS 4
#define ch2_textbook_PIVOT_X 4
#define ch2_textbook_PIVOT_Y 4
#define ch2_textbook_PIVOT_W 8
#define ch2_textbook_PIVOT_H 8
extern const metasprite_t* const ch2_textbook_metasprites[1];

BANKREF_EXTERN(ch2_textbook)

extern const palette_color_t ch2_textbook_palettes[4];
extern const uint8_t ch2_textbook_tiles[16];

#endif
