//AUTOGENERATED FILE FROM png2asset
// Conversion args: /ch2_cyclist.png -sw 16 -sh 32 -spr8x16 -o /ch2_cyclist.c

#ifndef METASPRITE_ch2_cyclist_H
#define METASPRITE_ch2_cyclist_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ch2_cyclist_TILE_ORIGIN 0
#define ch2_cyclist_TILE_W 8
#define ch2_cyclist_TILE_H 16
#define ch2_cyclist_WIDTH 16
#define ch2_cyclist_HEIGHT 32
#define ch2_cyclist_TILE_COUNT 4
#define ch2_cyclist_PALETTE_COUNT 1
#define ch2_cyclist_COLORS_PER_PALETTE 4
#define ch2_cyclist_TOTAL_COLORS 4
#define ch2_cyclist_PIVOT_X 8
#define ch2_cyclist_PIVOT_Y 16
#define ch2_cyclist_PIVOT_W 16
#define ch2_cyclist_PIVOT_H 32
extern const metasprite_t* const ch2_cyclist_metasprites[1];

BANKREF_EXTERN(ch2_cyclist)

extern const palette_color_t ch2_cyclist_palettes[4];
extern const uint8_t ch2_cyclist_tiles[64];

#endif
