//AUTOGENERATED FILE FROM png2asset
// Conversion args: /ch2_vendor.png -sw 32 -sh 32 -spr8x16 -o /ch2_vendor.c

#ifndef METASPRITE_ch2_vendor_H
#define METASPRITE_ch2_vendor_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ch2_vendor_TILE_ORIGIN 0
#define ch2_vendor_TILE_W 8
#define ch2_vendor_TILE_H 16
#define ch2_vendor_WIDTH 32
#define ch2_vendor_HEIGHT 32
#define ch2_vendor_TILE_COUNT 16
#define ch2_vendor_PALETTE_COUNT 1
#define ch2_vendor_COLORS_PER_PALETTE 4
#define ch2_vendor_TOTAL_COLORS 4
#define ch2_vendor_PIVOT_X 16
#define ch2_vendor_PIVOT_Y 16
#define ch2_vendor_PIVOT_W 32
#define ch2_vendor_PIVOT_H 32
extern const metasprite_t* const ch2_vendor_metasprites[1];

BANKREF_EXTERN(ch2_vendor)

extern const palette_color_t ch2_vendor_palettes[4];
extern const uint8_t ch2_vendor_tiles[256];

#endif
