//AUTOGENERATED FILE FROM png2asset
// Conversion args: /ch2_textbook.png -sw 8 -sh 8 -spr8x8 -o /ch2_textbook.c

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(ch2_textbook)

const palette_color_t ch2_textbook_palettes[4] = {
	RGB8(  0,  0,  0), RGB8(248,248,240), RGB8( 64, 96,176), RGB8( 40, 40, 48)
	};

const uint8_t ch2_textbook_tiles[16] = {
	0x00,0x00,0x7e,0x7e,0x42,0x7e,0x5a,0x66,0x5a,0x66,0x42,0x7e,0x7e,0x7e,0x00,0x00
	};

const metasprite_t ch2_textbook_metasprite0[] = {
	METASPR_ITEM(-4, -4, 0, S_PAL(0)),
	METASPR_TERM
};

const metasprite_t* const ch2_textbook_metasprites[1] = {
	ch2_textbook_metasprite0
};
