//AUTOGENERATED FILE FROM png2asset
// Conversion args: /ch2_baozi.png -sw 16 -sh 16 -spr8x16 -o /ch2_baozi.c

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(ch2_baozi)

const palette_color_t ch2_baozi_palettes[4] = {
	RGB8(  0,  0,  0), RGB8(248,248,240), RGB8(240,224,176), RGB8(240,200, 64)
	};

const uint8_t ch2_baozi_tiles[32] = {
	0x00,0x00,0x03,0x03,0x07,0x07,0x0f,0x0c,0x1f,0x10,0x3f,0x20,0x3f,0x00,0x3f,0x00,
	0x3f,0x00,0x3f,0x00,0x1f,0x20,0x0f,0x30,0x00,0x1f,0x00,0x0f,0x00,0x00,0x00,0x00
	};

const metasprite_t ch2_baozi_metasprite0[] = {
	METASPR_ITEM(-8, -8, 0, S_PAL(0)),
	METASPR_ITEM(0, 8, 0, S_PAL(0) | S_FLIPX),
	METASPR_TERM
};

const metasprite_t* const ch2_baozi_metasprites[1] = {
	ch2_baozi_metasprite0
};
