//AUTOGENERATED FILE FROM png2asset
// Conversion args: /ch2_textbook.png -sw 16 -sh 16 -spr8x16 -o /ch2_textbook.c

#ifndef METASPRITE_ch2_textbook_H
#define METASPRITE_ch2_textbook_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ch2_textbook_TILE_ORIGIN 0
#define ch2_textbook_TILE_W 8
#define ch2_textbook_TILE_H 16
#define ch2_textbook_WIDTH 16
#define ch2_textbook_HEIGHT 16
#define ch2_textbook_TILE_COUNT 2
#define ch2_textbook_PALETTE_COUNT 1
#define ch2_textbook_COLORS_PER_PALETTE 4
#define ch2_textbook_TOTAL_COLORS 4
#define ch2_textbook_PIVOT_X 8
#define ch2_textbook_PIVOT_Y 8
#define ch2_textbook_PIVOT_W 16
#define ch2_textbook_PIVOT_H 16
extern const metasprite_t* const ch2_textbook_metasprites[1];

BANKREF_EXTERN(ch2_textbook)

extern const palette_color_t ch2_textbook_palettes[4];
extern const uint8_t ch2_textbook_tiles[32];

#endif
