//AUTOGENERATED FILE FROM png2asset
// Conversion args: /ch2_baozi.png -sw 16 -sh 16 -spr8x16 -o /ch2_baozi.c

#ifndef METASPRITE_ch2_baozi_H
#define METASPRITE_ch2_baozi_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ch2_baozi_TILE_ORIGIN 0
#define ch2_baozi_TILE_W 8
#define ch2_baozi_TILE_H 16
#define ch2_baozi_WIDTH 16
#define ch2_baozi_HEIGHT 16
#define ch2_baozi_TILE_COUNT 2
#define ch2_baozi_PALETTE_COUNT 1
#define ch2_baozi_COLORS_PER_PALETTE 4
#define ch2_baozi_TOTAL_COLORS 4
#define ch2_baozi_PIVOT_X 8
#define ch2_baozi_PIVOT_Y 8
#define ch2_baozi_PIVOT_W 16
#define ch2_baozi_PIVOT_H 16
extern const metasprite_t* const ch2_baozi_metasprites[1];

BANKREF_EXTERN(ch2_baozi)

extern const palette_color_t ch2_baozi_palettes[4];
extern const uint8_t ch2_baozi_tiles[32];

#endif
