//AUTOGENERATED FILE FROM png2asset
// Conversion args: /ch2_bus.png -sw 24 -sh 16 -spr8x8 -o /ch2_bus.c

#ifndef METASPRITE_ch2_bus_H
#define METASPRITE_ch2_bus_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ch2_bus_TILE_ORIGIN 0
#define ch2_bus_TILE_W 8
#define ch2_bus_TILE_H 8
#define ch2_bus_WIDTH 24
#define ch2_bus_HEIGHT 16
#define ch2_bus_TILE_COUNT 6
#define ch2_bus_PALETTE_COUNT 1
#define ch2_bus_COLORS_PER_PALETTE 4
#define ch2_bus_TOTAL_COLORS 4
#define ch2_bus_PIVOT_X 12
#define ch2_bus_PIVOT_Y 8
#define ch2_bus_PIVOT_W 24
#define ch2_bus_PIVOT_H 16
extern const metasprite_t* const ch2_bus_metasprites[1];

BANKREF_EXTERN(ch2_bus)

extern const palette_color_t ch2_bus_palettes[4];
extern const uint8_t ch2_bus_tiles[96];

#endif
