//AUTOGENERATED FILE FROM png2asset
// Conversion args: /ch2_baozi.png -sw 8 -sh 8 -spr8x8 -o /ch2_baozi.c

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(ch2_baozi)

const palette_color_t ch2_baozi_palettes[4] = {
	RGB8(  0,  0,  0), RGB8(248,248,240), RGB8(240,224,176), RGB8(240,200, 64)
	};

const uint8_t ch2_baozi_tiles[16] = {
	0x18,0x18,0x3c,0x24,0x7e,0x42,0x7e,0x00,0x7e,0x00,0x3c,0x42,0x00,0x3c,0x00,0x00
	};

const metasprite_t ch2_baozi_metasprite0[] = {
	METASPR_ITEM(-4, -4, 0, S_PAL(0)),
	METASPR_TERM
};

const metasprite_t* const ch2_baozi_metasprites[1] = {
	ch2_baozi_metasprite0
};
