//AUTOGENERATED FILE FROM png2asset
// Conversion args: /ch2_dog_frame2.png -sw 16 -sh 8 -spr8x8 -o /ch2_dog_frame2.c

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(ch2_dog_frame2)

const palette_color_t ch2_dog_frame2_palettes[4] = {
	RGB8(  0,  0,  0), RGB8(216,168,112), RGB8(160, 96, 48), RGB8( 80, 48, 24)
	};

const uint8_t ch2_dog_frame2_tiles[32] = {
	0x00,0x00,0x00,0x00,0x00,0x07,0x00,0x0f,0x00,0x0f,0x00,0x02,0x00,0x01,0x02,0x02,
	0x0c,0x0c,0x1e,0x16,0x1c,0xf4,0x08,0xf8,0x00,0xf0,0x00,0x40,0x00,0x80,0x40,0x40
	};

const metasprite_t ch2_dog_frame2_metasprite0[] = {
	METASPR_ITEM(-4, -8, 0, S_PAL(0)),
	METASPR_ITEM(0, 8, 1, S_PAL(0)),
	METASPR_TERM
};

const metasprite_t* const ch2_dog_frame2_metasprites[1] = {
	ch2_dog_frame2_metasprite0
};
