//AUTOGENERATED FILE FROM png2asset
// Conversion args: /ch2_bus.png -sw 32 -sh 32 -spr8x16 -o /ch2_bus.c

#ifndef METASPRITE_ch2_bus_H
#define METASPRITE_ch2_bus_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ch2_bus_TILE_ORIGIN 0
#define ch2_bus_TILE_W 8
#define ch2_bus_TILE_H 16
#define ch2_bus_WIDTH 32
#define ch2_bus_HEIGHT 32
#define ch2_bus_TILE_COUNT 16
#define ch2_bus_PALETTE_COUNT 1
#define ch2_bus_COLORS_PER_PALETTE 4
#define ch2_bus_TOTAL_COLORS 4
#define ch2_bus_PIVOT_X 16
#define ch2_bus_PIVOT_Y 16
#define ch2_bus_PIVOT_W 32
#define ch2_bus_PIVOT_H 32
extern const metasprite_t* const ch2_bus_metasprites[1];

BANKREF_EXTERN(ch2_bus)

extern const palette_color_t ch2_bus_palettes[4];
extern const uint8_t ch2_bus_tiles[256];

#endif
