//AUTOGENERATED FILE FROM png2asset
// Conversion args: /ch2_pothole.png -sw 8 -sh 8 -spr8x8 -o /ch2_pothole.c

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(ch2_pothole)

const palette_color_t ch2_pothole_palettes[4] = {
	RGB8(  0,  0,  0), RGB8(176,176,176), RGB8(128,128,128), RGB8( 48, 48, 48)
	};

const uint8_t ch2_pothole_tiles[16] = {
	0x00,0x00,0x10,0x00,0x20,0x18,0x5a,0x3c,0x1c,0x3e,0x28,0x1c,0x0a,0x00,0x00,0x00
	};

const metasprite_t ch2_pothole_metasprite0[] = {
	METASPR_ITEM(-4, -4, 0, S_PAL(0)),
	METASPR_TERM
};

const metasprite_t* const ch2_pothole_metasprites[1] = {
	ch2_pothole_metasprite0
};
