//AUTOGENERATED FILE FROM png2asset
// Conversion args: /ch2_textbook.png -sw 16 -sh 16 -spr8x16 -o /ch2_textbook.c

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(ch2_textbook)

const palette_color_t ch2_textbook_palettes[4] = {
	RGB8(  0,  0,  0), RGB8(248,248,240), RGB8( 64, 96,176), RGB8( 40, 40, 48)
	};

const uint8_t ch2_textbook_tiles[32] = {
	0x00,0x00,0x1f,0x1f,0x1f,0x1f,0x10,0x1f,0x10,0x1f,0x13,0x1c,0x13,0x1c,0x13,0x1c,
	0x13,0x1c,0x10,0x1f,0x10,0x1f,0x10,0x1f,0x10,0x1f,0x1f,0x1f,0x1f,0x1f,0x00,0x00
	};

const metasprite_t ch2_textbook_metasprite0[] = {
	METASPR_ITEM(-8, -8, 0, S_PAL(0)),
	METASPR_ITEM(0, 8, 0, S_PAL(0) | S_FLIPX),
	METASPR_TERM
};

const metasprite_t* const ch2_textbook_metasprites[1] = {
	ch2_textbook_metasprite0
};
