//AUTOGENERATED FILE FROM png2asset
// Conversion args: /ch2_puddle.png -sw 8 -sh 8 -spr8x8 -o /ch2_puddle.c

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(ch2_puddle)

const palette_color_t ch2_puddle_palettes[4] = {
	RGB8(  0,  0,  0), RGB8( 96,160,224), RGB8( 64,112,176), RGB8( 32, 64,128)
	};

const uint8_t ch2_puddle_tiles[16] = {
	0x00,0x00,0x00,0x18,0x18,0x24,0x3c,0x42,0x3c,0x66,0x18,0x3c,0x00,0x18,0x00,0x00
	};

const metasprite_t ch2_puddle_metasprite0[] = {
	METASPR_ITEM(-4, -4, 0, S_PAL(0)),
	METASPR_TERM
};

const metasprite_t* const ch2_puddle_metasprites[1] = {
	ch2_puddle_metasprite0
};
