//AUTOGENERATED FILE FROM png2asset
// Conversion args: /ch2_puddle.png -sw 16 -sh 16 -spr8x16 -o /ch2_puddle.c

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(ch2_puddle)

const palette_color_t ch2_puddle_palettes[4] = {
	RGB8(  0,  0,  0), RGB8( 96,160,224), RGB8( 64,112,176), RGB8( 32, 64,128)
	};

const uint8_t ch2_puddle_tiles[32] = {
	0x00,0x00,0x00,0x00,0x00,0x03,0x03,0x0c,0x0f,0x10,0x1f,0x20,0x1f,0x20,0x0f,0x30,
	0x0f,0x38,0x1f,0x3c,0x0f,0x1f,0x03,0x0f,0x00,0x03,0x00,0x00,0x00,0x00,0x00,0x00
	};

const metasprite_t ch2_puddle_metasprite0[] = {
	METASPR_ITEM(-8, -8, 0, S_PAL(0)),
	METASPR_ITEM(0, 8, 0, S_PAL(0) | S_FLIPX),
	METASPR_TERM
};

const metasprite_t* const ch2_puddle_metasprites[1] = {
	ch2_puddle_metasprite0
};
