//AUTOGENERATED FILE FROM png2asset
// Conversion args: /ch2_dog_frame2.png -sw 32 -sh 16 -spr8x16 -o /ch2_dog_frame2.c

#ifndef METASPRITE_ch2_dog_frame2_H
#define METASPRITE_ch2_dog_frame2_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ch2_dog_frame2_TILE_ORIGIN 0
#define ch2_dog_frame2_TILE_W 8
#define ch2_dog_frame2_TILE_H 16
#define ch2_dog_frame2_WIDTH 32
#define ch2_dog_frame2_HEIGHT 16
#define ch2_dog_frame2_TILE_COUNT 6
#define ch2_dog_frame2_PALETTE_COUNT 1
#define ch2_dog_frame2_COLORS_PER_PALETTE 4
#define ch2_dog_frame2_TOTAL_COLORS 4
#define ch2_dog_frame2_PIVOT_X 16
#define ch2_dog_frame2_PIVOT_Y 8
#define ch2_dog_frame2_PIVOT_W 32
#define ch2_dog_frame2_PIVOT_H 16
extern const metasprite_t* const ch2_dog_frame2_metasprites[1];

BANKREF_EXTERN(ch2_dog_frame2)

extern const palette_color_t ch2_dog_frame2_palettes[4];
extern const uint8_t ch2_dog_frame2_tiles[96];

#endif
