//AUTOGENERATED FILE FROM png2asset
// Conversion args: /ch2_puddle.png -sw 16 -sh 16 -spr8x16 -o /ch2_puddle.c

#ifndef METASPRITE_ch2_puddle_H
#define METASPRITE_ch2_puddle_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ch2_puddle_TILE_ORIGIN 0
#define ch2_puddle_TILE_W 8
#define ch2_puddle_TILE_H 16
#define ch2_puddle_WIDTH 16
#define ch2_puddle_HEIGHT 16
#define ch2_puddle_TILE_COUNT 2
#define ch2_puddle_PALETTE_COUNT 1
#define ch2_puddle_COLORS_PER_PALETTE 4
#define ch2_puddle_TOTAL_COLORS 4
#define ch2_puddle_PIVOT_X 8
#define ch2_puddle_PIVOT_Y 8
#define ch2_puddle_PIVOT_W 16
#define ch2_puddle_PIVOT_H 16
extern const metasprite_t* const ch2_puddle_metasprites[1];

BANKREF_EXTERN(ch2_puddle)

extern const palette_color_t ch2_puddle_palettes[4];
extern const uint8_t ch2_puddle_tiles[32];

#endif
