//AUTOGENERATED FILE FROM png2asset
// Conversion args: /ch2_street_bg.png -map -use_map_attributes -tile_origin 128 -o /ch2_street_bg_data.c

#ifndef METASPRITE_ch2_street_bg_data_H
#define METASPRITE_ch2_street_bg_data_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ch2_street_bg_data_TILE_ORIGIN 128
#define ch2_street_bg_data_TILE_W 8
#define ch2_street_bg_data_TILE_H 8
#define ch2_street_bg_data_WIDTH 256
#define ch2_street_bg_data_HEIGHT 144
#define ch2_street_bg_data_TILE_COUNT 25
#define ch2_street_bg_data_PALETTE_COUNT 8
#define ch2_street_bg_data_COLORS_PER_PALETTE 4
#define ch2_street_bg_data_TOTAL_COLORS 32
#define ch2_street_bg_data_MAP_ATTRIBUTES ch2_street_bg_data_map_attributes
#define ch2_street_bg_data_MAP_ATTRIBUTES_WIDTH 32
#define ch2_street_bg_data_MAP_ATTRIBUTES_HEIGHT 18
#define ch2_street_bg_data_MAP_ATTRIBUTES_PACKED_WIDTH 32
#define ch2_street_bg_data_MAP_ATTRIBUTES_PACKED_HEIGHT 18
extern const unsigned char ch2_street_bg_data_map[576];
extern const unsigned char ch2_street_bg_data_map_attributes[576];

BANKREF_EXTERN(ch2_street_bg_data)

extern const palette_color_t ch2_street_bg_data_palettes[32];
extern const uint8_t ch2_street_bg_data_tiles[400];

#endif
