//AUTOGENERATED FILE FROM png2asset
// Conversion args: /ch2_cyclist.png -sw 8 -sh 16 -spr8x8 -o /ch2_cyclist.c

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(ch2_cyclist)

const palette_color_t ch2_cyclist_palettes[4] = {
	RGB8(  0,  0,  0), RGB8(232,190,150), RGB8(128,128,128), RGB8( 40, 40, 48)
	};

const uint8_t ch2_cyclist_tiles[32] = {
	0x00,0x00,0x18,0x18,0x3c,0x3c,0x3c,0x24,0x18,0x00,0x10,0x00,0x00,0x38,0x00,0x38,
	0x44,0x38,0x00,0x10,0x00,0x28,0x18,0x18,0x3c,0x3c,0x66,0x66,0x66,0x66,0x24,0x24
	};

const metasprite_t ch2_cyclist_metasprite0[] = {
	METASPR_ITEM(-8, -4, 0, S_PAL(0)),
	METASPR_ITEM(8, 0, 1, S_PAL(0)),
	METASPR_TERM
};

const metasprite_t* const ch2_cyclist_metasprites[1] = {
	ch2_cyclist_metasprite0
};
