//AUTOGENERATED FILE FROM png2asset
// Conversion args: /ch2_bike_frame1.png -sw 32 -sh 32 -spr8x16 -o /ch2_bike_frame1.c

#ifndef METASPRITE_ch2_bike_frame1_H
#define METASPRITE_ch2_bike_frame1_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ch2_bike_frame1_TILE_ORIGIN 0
#define ch2_bike_frame1_TILE_W 8
#define ch2_bike_frame1_TILE_H 16
#define ch2_bike_frame1_WIDTH 32
#define ch2_bike_frame1_HEIGHT 32
#define ch2_bike_frame1_TILE_COUNT 12
#define ch2_bike_frame1_PALETTE_COUNT 1
#define ch2_bike_frame1_COLORS_PER_PALETTE 4
#define ch2_bike_frame1_TOTAL_COLORS 4
#define ch2_bike_frame1_PIVOT_X 16
#define ch2_bike_frame1_PIVOT_Y 16
#define ch2_bike_frame1_PIVOT_W 32
#define ch2_bike_frame1_PIVOT_H 32
extern const metasprite_t* const ch2_bike_frame1_metasprites[1];

BANKREF_EXTERN(ch2_bike_frame1)

extern const palette_color_t ch2_bike_frame1_palettes[4];
extern const uint8_t ch2_bike_frame1_tiles[192];

#endif
