//AUTOGENERATED FILE FROM png2asset
// Conversion args: /ch3_npc_helper.png -b 255 -o /ch3_npc_helper.c

#ifndef METASPRITE_ch3_npc_helper_H
#define METASPRITE_ch3_npc_helper_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ch3_npc_helper_TILE_ORIGIN 0
#define ch3_npc_helper_TILE_W 8
#define ch3_npc_helper_TILE_H 16
#define ch3_npc_helper_WIDTH 16
#define ch3_npc_helper_HEIGHT 16
#define ch3_npc_helper_TILE_COUNT 4
#define ch3_npc_helper_PALETTE_COUNT 1
#define ch3_npc_helper_COLORS_PER_PALETTE 4
#define ch3_npc_helper_TOTAL_COLORS 4
#define ch3_npc_helper_PIVOT_X 8
#define ch3_npc_helper_PIVOT_Y 8
#define ch3_npc_helper_PIVOT_W 16
#define ch3_npc_helper_PIVOT_H 16
extern const metasprite_t* const ch3_npc_helper_metasprites[1];

BANKREF_EXTERN(ch3_npc_helper)

extern const palette_color_t ch3_npc_helper_palettes[4];
extern const uint8_t ch3_npc_helper_tiles[64];

#endif
