//AUTOGENERATED FILE FROM png2asset
// Conversion args: /ch3_player_down1.png -b 255 -o /ch3_player_down1.c

#ifndef METASPRITE_ch3_player_down1_H
#define METASPRITE_ch3_player_down1_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ch3_player_down1_TILE_ORIGIN 0
#define ch3_player_down1_TILE_W 8
#define ch3_player_down1_TILE_H 16
#define ch3_player_down1_WIDTH 16
#define ch3_player_down1_HEIGHT 16
#define ch3_player_down1_TILE_COUNT 4
#define ch3_player_down1_PALETTE_COUNT 1
#define ch3_player_down1_COLORS_PER_PALETTE 4
#define ch3_player_down1_TOTAL_COLORS 4
#define ch3_player_down1_PIVOT_X 8
#define ch3_player_down1_PIVOT_Y 8
#define ch3_player_down1_PIVOT_W 16
#define ch3_player_down1_PIVOT_H 16
extern const metasprite_t* const ch3_player_down1_metasprites[1];

BANKREF_EXTERN(ch3_player_down1)

extern const palette_color_t ch3_player_down1_palettes[4];
extern const uint8_t ch3_player_down1_tiles[64];

#endif
