//AUTOGENERATED FILE FROM png2asset
// Conversion args: /ch3_player_down2.png -b 255 -o /ch3_player_down2.c

#ifndef METASPRITE_ch3_player_down2_H
#define METASPRITE_ch3_player_down2_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ch3_player_down2_TILE_ORIGIN 0
#define ch3_player_down2_TILE_W 8
#define ch3_player_down2_TILE_H 16
#define ch3_player_down2_WIDTH 16
#define ch3_player_down2_HEIGHT 16
#define ch3_player_down2_TILE_COUNT 4
#define ch3_player_down2_PALETTE_COUNT 1
#define ch3_player_down2_COLORS_PER_PALETTE 4
#define ch3_player_down2_TOTAL_COLORS 4
#define ch3_player_down2_PIVOT_X 8
#define ch3_player_down2_PIVOT_Y 8
#define ch3_player_down2_PIVOT_W 16
#define ch3_player_down2_PIVOT_H 16
extern const metasprite_t* const ch3_player_down2_metasprites[1];

BANKREF_EXTERN(ch3_player_down2)

extern const palette_color_t ch3_player_down2_palettes[4];
extern const uint8_t ch3_player_down2_tiles[64];

#endif
