//AUTOGENERATED FILE FROM png2asset
// Conversion args: /ch3_airport.png -map -use_map_attributes -tile_origin 128 -b 255 -o /ch3_airport_data.c

#ifndef METASPRITE_ch3_airport_data_H
#define METASPRITE_ch3_airport_data_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ch3_airport_data_TILE_ORIGIN 128
#define ch3_airport_data_TILE_W 8
#define ch3_airport_data_TILE_H 8
#define ch3_airport_data_WIDTH 160
#define ch3_airport_data_HEIGHT 144
#define ch3_airport_data_TILE_COUNT 15
#define ch3_airport_data_PALETTE_COUNT 7
#define ch3_airport_data_COLORS_PER_PALETTE 4
#define ch3_airport_data_TOTAL_COLORS 28
#define ch3_airport_data_MAP_ATTRIBUTES ch3_airport_data_map_attributes
#define ch3_airport_data_MAP_ATTRIBUTES_WIDTH 20
#define ch3_airport_data_MAP_ATTRIBUTES_HEIGHT 18
#define ch3_airport_data_MAP_ATTRIBUTES_PACKED_WIDTH 20
#define ch3_airport_data_MAP_ATTRIBUTES_PACKED_HEIGHT 18
extern const unsigned char ch3_airport_data_map[360];
extern const unsigned char ch3_airport_data_map_attributes[360];

BANKREF_EXTERN(ch3_airport_data)

extern const palette_color_t ch3_airport_data_palettes[28];
extern const uint8_t ch3_airport_data_tiles[240];

#endif
