//AUTOGENERATED FILE FROM png2asset
// Conversion args: /ch3_npc_student.png -b 255 -o /ch3_npc_student.c

#ifndef METASPRITE_ch3_npc_student_H
#define METASPRITE_ch3_npc_student_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define ch3_npc_student_TILE_ORIGIN 0
#define ch3_npc_student_TILE_W 8
#define ch3_npc_student_TILE_H 16
#define ch3_npc_student_WIDTH 16
#define ch3_npc_student_HEIGHT 16
#define ch3_npc_student_TILE_COUNT 4
#define ch3_npc_student_PALETTE_COUNT 1
#define ch3_npc_student_COLORS_PER_PALETTE 4
#define ch3_npc_student_TOTAL_COLORS 4
#define ch3_npc_student_PIVOT_X 8
#define ch3_npc_student_PIVOT_Y 8
#define ch3_npc_student_PIVOT_W 16
#define ch3_npc_student_PIVOT_H 16
extern const metasprite_t* const ch3_npc_student_metasprites[1];

BANKREF_EXTERN(ch3_npc_student)

extern const palette_color_t ch3_npc_student_palettes[4];
extern const uint8_t ch3_npc_student_tiles[64];

#endif
